version: '3.8'

services:
  app:
    image: naaadang/cardinal:latest
    container_name: app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      REST_API_KEY: ${REST_API_KEY}
      KAKAO_URI: ${KAKAO_URI}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_SEC: ${ACCESS_SEC}
      REFRESH_SEC: ${REFRESH_SEC}
      ONE_TIME_CODE: ${ONE_TIME_CODE}
      ELASTIC_SEARCH_URI: ${ELASTIC_SEARCH_URI}
      ELASTIC_SEARCH_PASSWORD: ${ELASTIC_SEARCH_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

