spring:
  application:
    name: cardinal
  config:
      import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode:  never
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        transaction.jta.platform: org.hibernate.service.jta.JtaPlatform
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true  # 콘솔에 SQL 로그 출력
