apiVersion: v1
kind: Service

metadata:
  name: spring-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-redirect: '443'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: CERTIFICATE_ARN_PLACEHOLDER
  

spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    # 1. HTTPS 포트 설정 (추가)
    # 클라이언트의 443 포트 요청을 받아서
    - name: https
      protocol: TCP
      port: 443 
      # 파드의 8080 포트로 전달
      targetPort: 8080
      
    # 2. HTTP 포트 설정 (유지)
    # 클라이언트의 80 포트 요청을 받아서
    - name: http
      protocol: TCP
      port: 80
      # 파드의 8080 포트로 전달
      targetPort: 8080
